<div id="paypal-legacy" style="display:none;max-width:800px">
	<!-- <h2 class="wlm-integration-steps config-title"><?php _e('Legacy Instructions', 'wishlist-member') ;?> -->

	<h2 style="font-size:18px;width:100%;border:none;"><?php _e('Step 1. Create a "Buy Now" or "Subscribe" Button in Merchant Services Section of PayPal.<br>Create a button for each membership level using the Item/Subscription ID specified below','wishlist-member'); ?></h2>
	<blockquote>
		<p>
			* <?php _e('If you are creating a subscribe button and are using a Trial offer, please include the code in Step 5.<br />&nbsp;&nbsp;', 'wishlist-member'); ?>
		</p>
		<table class="widefat">
			<thead>
				<tr>
					<th scope="col" width="200"><?php _e('Membership Level', 'wishlist-member'); ?></th>
					<th scope="col"><?php _e('Item/Subscription ID', 'wishlist-member'); ?></th>
				</tr>
			</thead>
			<tbody>
				<?php $alt = 0;
				foreach ((array) $wpm_levels AS $sku => $level):
				?>
					<tr class="<?php echo $alt++ % 2 ? '' : 'alternate'; ?>" id="wpm_level_row_<?php echo $sku ?>">
						<td><b><?php echo $level['name'] ?></b></td>
						<td><u style="font-size:1.2em"><?php echo $sku ?></u></td>
				</tr>
				<?php
					endforeach; 
				?>
			</tbody>
		</table>
		<?php
		$pppsku_header = __('Item/Subscription ID', 'wishlist-member');
		include_once($this->pluginDir . '/admin/integration.shoppingcart-payperpost-skus.php');
		?>
	</blockquote>

	<h2 style="font-size:18px;width:100%;border:none;"><?php _e('Step 2. Set the "Thank You URL" of each product to the following URL:', 'wishlist-member'); ?></h2>
	<blockquote>
		<p>
			<a href="<?php echo $ppthankyou_url ?>" onclick="return false"><?php echo $ppthankyou_url ?></a>
		</p>
	</blockquote>

	<h2 style="font-size:18px;width:100%;border:none;"><?php _e('Step 3. Paste the code below in the "Add advanced variables" field:', 'wishlist-member'); ?></h2>
	<blockquote>
		<p>
			<b>rm=2<br />bn=WishListProducts_SP<br />notify_url=<?php echo $ppthankyou_url ?><br />return=<?php echo $ppthankyou_url ?></b>
		</p>
		<p>
			* <?php _e('This is located in PayPal\'s step 3 of creating a "Buy Now" button. It will say "Customize advanced features (optional)".', 'wishlist-member'); ?>
		</p>
	</blockquote>

	<h2 style="font-size:18px;width:100%;border:none;"><?php _e('Step 4. Paste the button code', 'wishlist-member'); ?></h2>
	<blockquote>
		<p>
			<?php _e('Paste the button code generated by Paypal to your sales Page.', 'wishlist-member'); ?>
		</p>
	</blockquote>

	<h2 style="font-size:18px;width:100%;border:none;"><?php _e('Step 5. Support for $0 Trial Subscriptions (Optional)', 'wishlist-member'); ?></h2>
	<blockquote>
		<p>
			<?php _e('Add the code below just before the &lt;/form&gt; tag of the Paypal button code to add support for $0 trial subscriptions.', 'wishlist-member'); ?>
		</p>
		<pre><strong>&lt;script type="text/javascript" src="<?php echo get_bloginfo('url'); ?>/?wlm_th=field:custom"&gt;&lt;/script&gt;</strong></pre>
		<p>
			<?php _e('Note: This also fixes the Paypal "Guest Payment" bug.', 'wishlist-member'); ?>
		</p>
	</blockquote>
</div>