<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

do_action( 'genesis_doctype' );
do_action( 'genesis_title' );
do_action( 'genesis_meta' );

wp_head(); // We need this for plugins.

?>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
</head>
<?php
genesis_markup( array(
	'open'   => '<body %s>',
	'context' => 'body',
) );
do_action( 'genesis_before' );

genesis_markup( array(
	'open'   => '<div %s>',
	'context' => 'site-container',
) );

do_action( 'genesis_before_header' );
do_action( 'genesis_header' );
do_action( 'genesis_after_header' );

genesis_markup( array(
	'open'   => '<div %s>',
	'context' => 'site-inner',
) );

?>

<div class="member-nav">
	<span class='mobile'><i class='fa fa-bars' aria-hidden='true'></i></span>
	<ul class="wrap">
		<li><a href="#my-units">My Units</a></li>
		<li><a href="#log-out">Log Out</a></li>
		<li><a href="#my-accounts">My Account</a></li>
		<li><a href="#search">Search</a></li>
	</ul>
</div>

<?php

genesis_structural_wrap( 'site-inner' );
