<?php

/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

do_action( 'genesis_doctype' );
do_action( 'genesis_title' );
do_action( 'genesis_meta' );

wp_head(); // We need this for plugins.

?>

</head>


<div class="member-nav">
	<div class="wrap">
		<span class='mobile'><i class='fa fa-bars closed' aria-hidden='true'></i></span>
		<ul>
			<li><a href="<?php echo site_url(); ?>/listing">My Units</a></li>
			<li><a href="<?php echo site_url(); ?>/wp-login.php?action=logout">Log Out</a></li>
			<li><a href="http://shop.plt.org/~userInfo">My Account</a></li>
			<li>
				<form role="search" method="get" class="search-form" action="<?php echo site_url(); ?>">

					<label>

						<input type="search" 
			                class="search-field" 
			                placeholder="Search"  
			                value="" name="s" 
			                title="Search efter:">

					</label>

					<input type="submit" class="search-submit" value="Search">

				</form>
			</li>
		</ul>
	</div>
</div>
<?php
genesis_markup( array(
	'open'   => '<body %s>',
	'context' => 'body',
) );
do_action( 'genesis_before' );

genesis_markup( array(
	'open'   => '<div %s>',
	'context' => 'site-container',
) );

?>

<header class="site-header" itemscope="" itemtype="http://schema.org/WPHeader">
	<div class="wrap">
	
		<div class="title-area">
			<p class="site-title eunit-title" itemprop="headline">
				<a href="<?php echo site_url(); ?>">Eunit</a>
			</p>
		</div>

		<?php 

			$type = get_post_type($post->ID);
			$cat_ids = wp_get_post_categories($post->ID);
			// var_dump($cat_ids);
			if(in_array(15, $cat_ids)){
				$cat = 'climate';
				$thumb_id = 391;
				$activity = "Carbon & Climate";
			}

			if(in_array(51, $cat_ids)){
				$cat = 'energy';
				$thumb_id = 1865;
				$activity = "Energy in Ecosystems";
			}
			
			if(in_array(89, $cat_ids)){
				$cat = 'treemendous';
				$thumb_id = 3339;
				$activity = "Treemendous Science!";
			}

			$GLOBALS['thumb_id'] = $thumb_id;
			$GLOBALS['activity'] = $activity;
			
		?>
		<?php if($cat == 'climate'){ ?>
			<div class="widget-area header-widget-area">
				<section id="nav_menu-2" class="widget widget_nav_menu">
					<div class="widget-wrap">
						<nav class="nav-header" itemscope="" itemtype="http://schema.org/SiteNavigationElement">
							<ul class="grade-levels-nav unit-nav">
								<li>
									<a href="<?php echo site_url(); ?>/unit-topic/carbon-and-climate/">
										<h1>Carbon & Climate</h1>

										<img src="<?php echo get_bloginfo('stylesheet_directory'); ?>/images/6-8-icon.png">
									</a>
								</li>
							</ul>
					
						</nav>
					</div>
				</section>

			</div>
		<?php } elseif($cat == 'energy'){ ?>
			<div class="widget-area header-widget-area">
				<section id="nav_menu-2" class="widget widget_nav_menu">
					<div class="widget-wrap">
						<nav class="nav-header" itemscope="" itemtype="http://schema.org/SiteNavigationElement">
							
							<ul class="grade-levels-nav unit-nav">
								<li>
									<a href="<?php echo site_url(); ?>/unit-topic/carbon-and-climate/">
										<h1>Energy In Ecosystems</h1>
										<img src="<?php echo get_bloginfo('stylesheet_directory'); ?>/images/3-5-icon.png">
									</a>
								</li>
							</ul>
					
						</nav>
					</div>
				</section>
			</div>
		<?php } elseif($cat == 'treemendous'){ ?>
			<div class="widget-area header-widget-area">
				<section id="nav_menu-2" class="widget widget_nav_menu">
					<div class="widget-wrap">
						<nav class="nav-header" itemscope="" itemtype="http://schema.org/SiteNavigationElement">
							
							<ul class="grade-levels-nav unit-nav">
								<li>
									<a href="<?php echo site_url(); ?>/unit-topic/treemendous-science/">
										<h1>Treemendous Science!</h1>
										<img src="<?php echo get_bloginfo('stylesheet_directory'); ?>/images/k-2-icon.png">
									</a>
								</li>
							</ul>
					
						</nav>
					</div>
				</section>
			</div>
		<?php } else { ?>
			<div class="widget-area header-widget-area">
				<section id="nav_menu-2" class="widget widget_nav_menu">
					<div class="widget-wrap">
						<nav class="nav-header" itemscope="" itemtype="http://schema.org/SiteNavigationElement">
							
							<ul class="grade-levels-nav">
								<li>
									<a href="<?php echo site_url(); ?>/listing/k-2">
									<img src="<?php echo get_bloginfo( 'stylesheet_directory' ); ?>/images/k-2.png" alt="k-2">
									</a></li>
								<li>
									<a href="<?php echo site_url(); ?>/listing/3-5">
									<img src="<?php echo get_bloginfo( 'stylesheet_directory' ); ?>/images/3-5.png" alt="3-5">
									</a></li>
								<li>
									<a href="<?php echo site_url(); ?>/listing/6-8">
									<img src="<?php echo get_bloginfo( 'stylesheet_directory' ); ?>/images/6-8.png" alt="6-8">
									</a></li>
							</ul>
					
						</nav>
					</div>
				</section>

			</div>
			
		<?php } ?>
	</div>
</header>

<?php
genesis_markup( array(
	'open'   => '<div %s>',
	'context' => 'site-inner',
) );
?>


<?php

genesis_structural_wrap( 'site-inner' );
