<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
genesis_markup( array(
	'close'   => '</div>',
	'context' => 'site-inner',
) );

do_action( 'genesis_before_footer' );
?>
<div class="member-nav-footer">
	<div class="wrap">
		<ul class="copyright">
			<li>&#169; 2016, American Forest Foundation</li>
			<li><a target="_blank" href="https://www.plt.org/about-us/privacy-policy/">Privacy Policy</a> PLT is a program of the American Forest Foundation</li>
			
		</ul>
		<ul class="social">
			<li><a target="_blank" href="http://facebook.com/projectlearningtree"><img src="<?php echo get_bloginfo('stylesheet_directory'); ?>/images/facebook.png" alt=""></a></li>
			<li><a target="_blank" href="http://pinterest.com/nationalplt"><img src="<?php echo get_bloginfo('stylesheet_directory'); ?>/images/pinterest.png" alt=""></a></li>
			<li><a target="_blank" href="http://twitter.com/plt"><img src="<?php echo get_bloginfo('stylesheet_directory'); ?>/images/twitter.png" alt=""></a></li>
			<li><a target="_blank" href="http://youtube.com/user/ProjectLearningTree"><img src="<?php echo get_bloginfo('stylesheet_directory'); ?>/images/youtube.png" alt=""></a></li>
		</ul>
		<ul class="support">
			<li><a href="<?php echo site_url(); ?>/support">Support</a></li>
			<li><a href="http://shop.plt.org/~userInfo">My Account</a></li>
		</ul>
	</div>
</div>
<?php

do_action( 'genesis_after_footer' );

genesis_markup( array(
	'close'   => '</div>',
	'context' => 'site-container',
) );

do_action( 'genesis_after' );
wp_footer(); // We need this for plugins.

genesis_markup( array(
	'close'   => '</body>',
	'context' => 'body',
) );

?>
<script type='text/javascript'>
(function (d, t) {
  var bh = d.createElement(t), s = d.getElementsByTagName(t)[0];
  bh.type = 'text/javascript';
  bh.src = 'https://www.bugherd.com/sidebarv2.js?apikey=wwniha5cvbodmcxyngv4lq';
  s.parentNode.insertBefore(bh, s);
  })(document, 'script');
</script>
</html>
